### ISSUE TITLE
Consider ignoring fields instead of failing to encode

### ISSUE THREAD

**Issue by eblocha** [tychedelia/kafka-protocol-rs#85]
Currently the library will fail encoding if fields are set on requests when those fields are only relevant to newer api versions.

For example: https://github.com/tychedelia/kafka-protocol-rs/blob/main/src/messages/metadata_request.rs#L108

I am working on a Kafka client that can dynamically select a version based on the broker version range. Since the request will fail to encode based on the version selected, the creator of the message needs to know the version before creating it.

However, the client I am working on lazily connects and resolves versions only when a request is sent, so this version information is not available at creation time.

Could the encoders ignore fields that aren't relevant to the version being encoded?

**Comment by tychedelia** [comment]
Maybe we could explore adding this is a configurable option, but it definitely wouldn't be the correct default behavior. If you want to fork the library, this should be pretty easy to replace yourself, although I have to admit I'm a bit skeptical about your ability to generalize this approach... new protocol fields are semantically meaningful relative to the expected behavior of the broker, so at some point, the caller does indeed need to know the version of the broker they're interacting with to accomplish anything useful.

**Comment by eblocha** [comment]
Fair enough. It looks like the official Java client requires the version to create messages (and throws if incompatible), so this is equivalent.

I think I can change the approach I'm taking to acquire a connection first before creating the message.
